/**
 * Security Gate Script - CI/CD Pipeline Quality Gate Enforcement
 * 
 * This script is the critical security checkpoint in the GitOps pipeline.
 * It analyzes security scan reports and determines whether a deployment
 * should proceed based on vulnerability thresholds and security policies.
 * 
 * The script evaluates:
 * - Software Composition Analysis (SCA) results from npm audit or OWASP Dependency-Check
 * - Container image vulnerabilities from Trivy scans
 * - Secret detection results from Gitleaks
 * 
 * Exit codes:
 * - 0: Security gate passed, deployment can proceed
 * - 1: Security gate failed due to policy violations
 * - 2: Script execution error (missing files, parsing errors)
 * 
 * Environment Variables:
 * - SCA_REPORT: Path to SCA report (default: reports/sca/npm-audit-report.json)
 * - IMAGE_REPORT: Path to image scan report (default: reports/image/trivy-image.json)
 * - SECRET_REPORT: Path to secret scan report (default: reports/secret/gitleaks-report.json)
 * - GATE_CRITICAL_THRESHOLD: Max allowed critical vulnerabilities (default: 0)
 * - GATE_HIGH_THRESHOLD: Max allowed high vulnerabilities (default: 20)
 */

const fs = require('fs');

// Define default paths for security reports generated by the pipeline
// These paths correspond to the report directories created in the Jenkinsfile
const files = {
  sca: process.env.SCA_REPORT || 'reports/sca/npm-audit-report.json',        // Software Composition Analysis
  image: process.env.IMAGE_REPORT || 'reports/image/trivy-image.json',        // Container image scan
  secret: process.env.SECRET_REPORT || 'reports/secret/gitleaks-report.json'  // Secret detection
};

// Define severity levels that will cause the security gate to fail
// Only CRITICAL and HIGH vulnerabilities are considered blocking
const sevOrder = ['CRITICAL', 'HIGH'];

/**
 * Safely reads and parses a JSON file with error handling
 * 
 * This function ensures that required security reports exist and are valid JSON.
 * Missing reports will cause the security gate to fail, preventing deployment
 * of potentially vulnerable code.
 * 
 * @param {string} path - File path to read
 * @returns {object} - Parsed JSON object
 * @throws {Error} - If file doesn't exist or JSON is invalid
 */
function safeReadJson(path) {
  if (!fs.existsSync(path)) {
    throw new Error(`Required report not found: ${path}`);
  }
  
  try {
    return JSON.parse(fs.readFileSync(path, 'utf8'));
  } catch (parseError) {
    throw new Error(`Invalid JSON in report ${path}: ${parseError.message}`);
  }
}

/**
 * Analyzes Software Composition Analysis (SCA) report for vulnerabilities
 * 
 * This function handles two different SCA report formats:
 * 1. npm audit format (preferred for Node.js projects)
 * 2. OWASP Dependency-Check format (legacy support)
 * 
 * The function extracts vulnerability counts by severity level and creates
 * a list of vulnerability identifiers for detailed reporting.
 * 
 * @param {object} report - Parsed SCA report JSON
 * @returns {object} - Findings object with counts and vulnerability IDs
 */
function getScaFindings(report) {
  const findings = { CRITICAL: 0, HIGH: 0, ids: [] };

  // Handle OWASP Dependency-Check format
  // This format has a 'dependencies' array with nested vulnerabilities
  if (report.dependencies && Array.isArray(report.dependencies)) {
    report.dependencies.forEach(dep => {
      if (dep.vulnerabilities && Array.isArray(dep.vulnerabilities)) {
        dep.vulnerabilities.forEach(vuln => {
          // Normalize severity field (different tools use different casing)
          const sev = String(vuln.severity || vuln.Severity || '').toUpperCase();
          
          // Only count CRITICAL and HIGH vulnerabilities
          if (findings[sev] !== undefined) {
            findings[sev]++;
            // Create descriptive identifier for reporting
            findings.ids.push(`${vuln.name || vuln.id || 'Unknown'} (SCA: ${dep.fileName || 'manifest'})`);
          }
        });
      }
    });
    return findings;
  }

  // Handle npm audit format (metadata.vulnerabilities summary)
  // This format provides pre-aggregated vulnerability counts
  if (report.metadata && report.metadata.vulnerabilities) {
    const v = report.metadata.vulnerabilities;
    findings.CRITICAL = v.critical || 0;
    findings.HIGH = v.high || 0;
    
    // npm audit doesn't provide individual vulnerability IDs in metadata
    // In a production system, you might parse the 'vulnerabilities' object
    // to extract specific CVE identifiers
    
    return findings;
  }
  
  // Return empty findings if report format is unrecognized
  return findings;
}

/**
 * Analyzes Trivy container image scan report for vulnerabilities
 * 
 * Trivy scans container images for:
 * - OS package vulnerabilities
 * - Application dependency vulnerabilities
 * - Configuration issues
 * 
 * The function processes the Results array and extracts vulnerability
 * information including CVE IDs and affected packages.
 * 
 * @param {object} report - Parsed Trivy image scan report
 * @returns {object} - Findings object with counts and vulnerability IDs
 */
function getImageFindings(report) {
  const findings = { CRITICAL: 0, HIGH: 0, ids: [] };
  
  // Trivy report structure: { Results: [{ Vulnerabilities: [...] }] }
  for (const result of report.Results || []) {
    for (const vuln of result.Vulnerabilities || []) {
      // Normalize severity field (Trivy uses 'Severity')
      const sev = String(vuln.Severity || vuln.severity || '').toUpperCase();
      
      // Only count CRITICAL and HIGH vulnerabilities
      if (findings[sev] !== undefined) {
        findings[sev]++;
        // Create descriptive identifier with CVE ID and package name
        findings.ids.push(`${vuln.VulnerabilityID || vuln.id} (Image: ${vuln.PkgName || 'OS'})`);
      }
    }
  }
  
  return findings;
}

// Define security policy thresholds
// These can be customized via environment variables to match organizational policies
const thresholds = {
  CRITICAL: parseInt(process.env.GATE_CRITICAL_THRESHOLD || '0', 10),   // Zero tolerance for critical vulns
  HIGH: parseInt(process.env.GATE_HIGH_THRESHOLD || '20', 10)           // Allow up to 20 high vulns
};

/**
 * Main Security Gate Execution
 * 
 * This is the core logic that determines whether a deployment should proceed.
 * The script follows these steps:
 * 
 * 1. Read and parse all security reports
 * 2. Extract vulnerability counts from each report
 * 3. Aggregate findings across all scan types
 * 4. Compare against defined thresholds
 * 5. Check for any detected secrets
 * 6. Make pass/fail decision and exit with appropriate code
 */
try {
  console.log('🛡️  Starting Security Gate Evaluation...');
  console.log(`Thresholds: Critical <= ${thresholds.CRITICAL}, High <= ${thresholds.HIGH}`);
  
  // Handle flexible SCA report paths
  // Try npm audit format first, fall back to OWASP Dependency-Check
  let scaPath = files.sca;
  if (!fs.existsSync(scaPath)) {
    const odcPath = 'reports/sca/dependency-check-report.json';
    if (fs.existsSync(odcPath)) {
      console.log('Using OWASP Dependency-Check report format');
      scaPath = odcPath;
    }
  } else {
    console.log('Using npm audit report format');
  }

  // Parse all security reports
  console.log('📊 Reading security reports...');
  const scaFindings = getScaFindings(safeReadJson(scaPath));
  const imageFindings = getImageFindings(safeReadJson(files.image));
  
  // Handle secret detection report (Gitleaks format is an array of findings)
  const secretReport = safeReadJson(files.secret);
  const secretCount = Array.isArray(secretReport) ? secretReport.length : 0;

  // Aggregate vulnerability counts across all scan types
  const total = {
    CRITICAL: scaFindings.CRITICAL + imageFindings.CRITICAL,
    HIGH: scaFindings.HIGH + imageFindings.HIGH
  };
  
  // Combine all vulnerability identifiers for detailed reporting
  const allIds = [...scaFindings.ids, ...imageFindings.ids];

  // Display comprehensive security gate results
  console.log('---------------------------------------------------------');
  console.log('🛡️  SECURITY GATE EVALUATION RESULTS');
  console.log('---------------------------------------------------------');
  console.log(`📦 SCA Findings:     Critical=${scaFindings.CRITICAL}, High=${scaFindings.HIGH}`);
  console.log(`🐳 Image Findings:   Critical=${imageFindings.CRITICAL}, High=${imageFindings.HIGH}`);
  console.log(`🔐 Secrets Found:    ${secretCount}`);
  console.log('---------------------------------------------------------');
  console.log(`📊 Total Critical:   ${total.CRITICAL} (threshold: ${thresholds.CRITICAL})`);
  console.log(`📊 Total High:       ${total.HIGH} (threshold: ${thresholds.HIGH})`);
  console.log('---------------------------------------------------------');

  // Evaluate security policy violations
  const failedCritical = total.CRITICAL > thresholds.CRITICAL;
  const failedHigh = total.HIGH > thresholds.HIGH;
  const hasSecrets = secretCount > 0;

  // Security gate failure logic
  if (failedCritical || failedHigh || hasSecrets) {
    console.error('❌ SECURITY GATE FAILED - DEPLOYMENT BLOCKED');
    console.error('==========================================================');
    
    // Provide specific failure reasons
    if (failedCritical) {
      console.error(`🚨 CRITICAL: Found ${total.CRITICAL} critical vulnerabilities (max allowed: ${thresholds.CRITICAL})`);
    }
    if (failedHigh) {
      console.error(`⚠️  HIGH: Found ${total.HIGH} high vulnerabilities (max allowed: ${thresholds.HIGH})`);
    }
    if (hasSecrets) {
      console.error(`🔐 SECRETS: Found ${secretCount} exposed secret(s) - immediate remediation required`);
    }

    // List specific vulnerabilities for remediation guidance
    if (allIds.length > 0) {
      console.error('\n🔍 Vulnerabilities requiring attention:');
      allIds.forEach(id => console.error(`  • ${id}`));
    }
    
    console.error('==========================================================');
    console.error('🛑 Deployment blocked. Fix vulnerabilities and retry.');
    console.error('==========================================================');
    
    // Exit with failure code to stop the CI/CD pipeline
    process.exit(1);
  }

  // Security gate success
  console.log('✅ SECURITY GATE PASSED - DEPLOYMENT APPROVED');
  console.log('==========================================================');
  
  // Show informational findings that don't block deployment
  if (allIds.length > 0) {
    console.log('\n📋 Non-blocking findings detected (below threshold):');
    allIds.forEach(id => console.log(`  • ${id}`));
    console.log('\n💡 Consider addressing these in future releases.');
  } else {
    console.log('🎉 No security vulnerabilities detected!');
  }
  
  console.log('==========================================================');
  console.log('🚀 Proceeding with deployment...');

} catch (err) {
  // Handle script execution errors
  console.error('💥 SECURITY GATE EXECUTION ERROR');
  console.error('==========================================================');
  console.error(`Error: ${err.message}`);
  console.error('==========================================================');
  console.error('🛑 Cannot evaluate security posture. Deployment blocked.');
  
  // Exit with error code to indicate script failure
  process.exit(2);
}
